import { QuestionTypes } from "@/helpers/types";

export const questionsDummy: QuestionTypes[] = [
  {
    questionText: "What is the capital of France?",
    questionType: "multiple-choice",
    options: ["Berlin", "Madrid", "Paris", "Rome"],
    correctAnswer: "Paris",
    explanation: "Paris is the capital city of France.",
    questionPoints: 5, // Added questionPoints
    difficulty: "easy", // Added difficulty
  },
  {
    questionText: "Which of the following is a JavaScript framework?",
    questionType: "multiple-choice",
    options: ["React", "Laravel", "Django", "Flask"],
    correctAnswer: "React",
    explanation: "React is a popular JavaScript framework for building user interfaces.",
    questionPoints: 5,
    difficulty: "easy",
  },
  {
    questionText: "List the three primary colors.",
    questionType: "enumeration",
    options: [],
    correctAnswer: ["Red", "Blue", "Yellow"],
    explanation: "The primary colors are red, blue, and yellow because they cannot be created by mixing other colors.",
    questionPoints: 3,
    difficulty: "medium",
  },
  {
    questionText: "Name the planets in our solar system in order from the Sun.",
    questionType: "enumeration",
    options: [],
    correctAnswer: [
      "Mercury",
      "Venus",
      "Earth",
      "Mars",
      "Jupiter",
      "Saturn",
      "Uranus",
      "Neptune",
    ],
    explanation: "These are the planets in order of their distance from the Sun.",
    questionPoints: 10,
    difficulty: "hard",
  },
  {
    questionText: "What is the chemical symbol for water?",
    questionType: "identification",
    options: [],
    correctAnswer: "H2O",
    explanation: "Water is represented by the chemical formula H2O, which consists of two hydrogen atoms and one oxygen atom.",
    questionPoints: 5,
    difficulty: "easy",
  },
  {
    questionText: "Who wrote the play 'Romeo and Juliet'?",
    questionType: "identification",
    options: [],
    correctAnswer: "William Shakespeare",
    explanation: "William Shakespeare, an English playwright, wrote 'Romeo and Juliet.'",
    questionPoints: 5,
    difficulty: "medium",
  },
  {
    questionText: "Explain the importance of photosynthesis in the ecosystem.",
    questionType: "essay",
    options: [],
    correctAnswer: null,
    explanation: "Photosynthesis is crucial as it converts light energy into chemical energy, producing oxygen and sustaining life.",
    questionPoints: 10,
    difficulty: "hard",
  },
  {
    questionText: "Describe the impact of the Industrial Revolution on modern society.",
    questionType: "essay",
    options: [],
    correctAnswer: null,
    explanation: "The Industrial Revolution led to technological advancements, urbanization, and significant economic and social changes.",
    questionPoints: 10,
    difficulty: "hard",
  },
  {
    questionText: "What is the powerhouse of the cell?",
    questionType: "identification",
    options: [],
    correctAnswer: "Mitochondria",
    explanation: "The mitochondria generate ATP, providing energy to the cell.",
    questionPoints: 5,
    difficulty: "easy",
  },
  {
    questionText: "Name any three programming languages.",
    questionType: "enumeration",
    options: [],
    correctAnswer: ["JavaScript", "Python", "C++"],
    explanation: "JavaScript, Python, and C++ are widely used programming languages.",
    questionPoints: 5,
    difficulty: "medium",
  },
];
